content/changes.md
scripts/import_product_releases.py

Adds a synopsis placeholder per [this comment](https://github.com/andela-technology/qualified-docs/pull/204#issuecomment-2093828342).

Add synopsis to changelog template

---

content/changes.md

https://andela.atlassian.net/browse/QUAL-1111

[QUAL-1111] Fix accuracy of new language messages in changelog

---

content/changes.md

Adding the release notes information generated in February 2024
https://andela.atlassian.net/browse/QUAL-1110

[QUAL-1110] Product Updates February 2024

---

src/components/ToggleDarkMode.vue

See https://andela.atlassian.net/browse/QUAL-1103.
The idea here is to avoid uncaught errors percolating up to the main app, which are [ugly](https://andela.atlassian.net/browse/QUAL-1102). While at it, the code quality can be improved a bit.
To review, make sure there are no regressions in dark mode. You should be able to toggle it with the UI switch, set it via the `?theme=light` or `?theme=dark` URL query parameter, persist it in local storage, and use it properly in an iframe (preview any challenge and click on the IDE Help tab).
[Deploy preview](https://deploy-preview-203--fervent-mayer-2fb2ca.netlify.app/) (you can check everything here except the iframe part, which requires running locally and adjusting a URL in [docs-pane.tpl.html](https://github.com/andela-technology/qualified/pul …

[QUAL-1103] Improve dark mode error handling and code

---

content/changes.md

Considering big part of the team has been working on Pathways during this month I think these are the most relevant changes to share with our users.

[QUAL-1117]Product Updates March 2024

---

content/changes.md

Added the most relevant changes we released during April 2024.

[QUAL-1133] Product Updates April 2024

---

content/reference/printing.md

https://andela.atlassian.net/browse/QUAL-1235

[QUAL-1235] Update windows printing

---

content/creating-content/challenges/guides.md
content/creating-content/challenges/guides/managing-third-party-dependencies.md
content/creating-content/challenges/upgrading-language-versions.md

https://andela.atlassian.net/browse/QUAL-1248

Add Managing Third-Party Dependencies guide

---

content/integrations/custom-integrations/embed.md

https://andela.atlassian.net/browse/QUAL-1250

[QUAL-1250] Update Embed links

---

content/reference/languages/typescript.md

Merge once https://github.com/andela-technology/exo-images/pull/503/ is merged and a [template](https://andela.atlassian.net/browse/QUAL-1214) has verified that it works. https://andela.atlassian.net/browse/QUAL-1215

Add express-joi-validation and joi to TS 4.9

---

content/changes.md

Most of the work we have been doing during June was internally so I think this is the most valuable information we can share with our customers.

[QUAL-1341] Product Updates June 2024

---

content/reference/languages/clojure.md

https://andela.atlassian.net/browse/QUAL-1387

Fix clojure test link

---

content/creating-content/challenges/guides.md
content/creating-content/challenges/guides/gpt-validation.md

https://andela.atlassian.net/browse/QUAL-1422

Add GPT validation guide

---

content/creating-content/challenges/guides/gpt-validation.md

https://andela.atlassian.net/browse/QUAL-1438

Add GPT ideas

---

content/creating-content/challenges/guides/gpt-validation.md

https://andela.atlassian.net/browse/QUAL-1475

Improve GPT validation analytics

---

content/creating-content/challenges/guides.md
content/creating-content/challenges/guides/gpt-validation-testing.md
content/creating-content/challenges/guides/gpt-validation.md

https://andela.atlassian.net/browse/QUAL-1495

Add initial GPT validation testing guide

---

content/reference/features/challenges/multi-file-code/index.md

Merge once https://andela.atlassian.net/browse/QUAL-1588 is merged.

Document disablewebpreview query param for web preview

---

content/changes.md

With the purpose of keeping our users warm and updated we want to add to the Product Updates section the features released during August 2024.
[Jira Query](https://andela.atlassian.net/issues/?jql=project%20%3D%20QUAL%0AAND%20text%20~%20%22Add%20%22%0AAND%20fixversion%20IN%20%28%22Release%20-%202024.32.1%22%2C%20%22Release%20-%202024.32.2%22%2C%20%22Release%20-%202024.33.1%22%2C%20%22Release%20-%202024.34.1%22%2C%20%22Release%20-%202024.35.1%22%29%0AORDER%20BY%20created%20DESC)

[QUAL-1748] Product Updates - Release Notes August 2024

---

content/changes.md

Remove a typo in the new quiz title added

Remove a typo

---

content/changes.md

The relevant improvements we have released during September 2024.

[QUAL-1757] Product Updates September 2024

---

content/changes.md

This feature is only accessible when the following Labs Features are enabled:  External Ide and Solutions Review Dialog Preview.

[QUAL-1757] Explain better what needs to be enabled to get access to the Quick Review menu option

---

content/changes.md

With the purpose of keeping our users warm and updates of our most relevant and recent updates we are updating the Product Updates page including the last releases we did during October, November and December.

[QUAL-1810] Product Updates for October, November and December
